### ISSUE TITLE
tmpl folder gets blocked by precommit sops

### ISSUE THREAD

**Issue by axlroden** [k8s-at-home/flux-cluster-template#358]
# Details

**How to ignore tmpl folder:**

I did not clone this repo, just took some things, so my question is, how are you ignoring the tmpl folder for the precommit of sops ? I can't seem to find where it gets ignored.. should I just do:
```yaml
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
        exclude: ^tmpl
```
 
or what is the preferred method ?
