### ISSUE TITLE
❓ Wildcard domains

### ISSUE THREAD

**Issue by rustygreen** [k8s-at-home/flux-cluster-template#415]
# Details

Why not use a wildcard domain for this template?

I assume we could just add this to the cluster issuer(s):
```yaml
selector:
  dnsZones:
    - ${SECRET_DOMAIN}
    - *.${SECRET_DOMAIN}
```
Wouldn't this reduce the certificate requests/orders?
